cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.index, name="index"),
    path("pais/list/", views.pais_list, name="pais_list"),
    path("cliente/list/", views.cliente_list, name="cliente_list"),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index),
    path("saludar/", views.saludar),
    path("saludar2/", views.saludar_con_etiqueta),
    path("saludar-param/<str:nombre>/<str:apellido>", views.saludar_con_parametros),
    path("tirar-dado/", views.tirar_dado),
    path("ejercicio/", views.ejercicio),
    path("ver-notas/", views.notas),
    path("ejercicio2/", views.ejercicio2),
]

config/urls.py
from django.contrib import admin
from django.urls import path

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("saludar/", views.saludar),
    path("saludar/2", views.saludar_con_etiqueta)
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

producto/urls.py
from django.urls import path

from . import views

app_name = "producto"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "productocategoria/list/",
        views.productocategoria_list,
        name="productocategoria_list",
    ),
    path(
        "productocategoria/create/",
        views.productocategoria_create,
        name="productocategoria_create",
    ),
]

cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.nombre


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen = models.ForeignKey(
        Pais, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self) -> str:
        return f"{self.apellido.upper()}, {self.nombre}"

core/models.py
from django.db import models

# Create your models here.

producto/models.py
from django.db import models


class ProductoCategoria(models.Model):
    """Categorías de productos"""

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Categoría de Producto"
        verbose_name_plural = "Categorías de Productos"

producto/forms.py
from django import forms
from . import models


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"

cliente/views.py
from django.shortcuts import render

from .models import Pais, Cliente


def index(request):
    return render(request, "cliente/index.html")


def pais_list(request):
    paises = Pais.objects.all()
    contexto = {"paises": paises}
    return render(request, "cliente/pais_list.html", contexto)


def cliente_list(request):
    clientes = Cliente.objects.all()
    contexto = {"clientes": clientes}
    return render(request, "cliente/cliente_list.html", contexto)

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, "core/index.html")

producto/views.py
from django.shortcuts import render, redirect

from . import models, forms


def index(request):
    return render(request, "producto/index.html")


def productocategoria_list(request):
    productocategoria = models.ProductoCategoria.objects.all()
    contexto = {"productocategoria": productocategoria}
    return render(request, "producto/productocategoria_list.html", contexto)


def productocategoria_create(request):
    if request.method == "GET":
        form = forms.ProductoCategoriaForm()
    if request.method == "POST":
        form = forms.ProductoCategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("producto:productocategoria_list")

    contexto = {"form": form}
    return render(request, "producto/productocategoria_create.html", contexto)

cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block title %}
    Clientes    
{% endblock title %}

{% block content %}
    <a href="{% url 'cliente:pais_list' %}">Listar países</a>
    <a href="{% url 'cliente:cliente_list' %}">Listar clientes</a>
    <button>
        <a href="/">Inicio</a>
    </button>    
{% endblock content %}

cliente/templates/cliente/pais_list.html
{% extends 'core/base.html' %}

{% block title %}
    Países de origen
{% endblock title %}

{% block content %}
    <button>
        <a href="{% url 'cliente:index' %}">Volver</a>
    </button>    
    {% for pais in paises %}
        <p> {{ pais }} </p>
    {% endfor %}
{% endblock content %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coderhouse</title>
</head>
<body style="display:grid; justify-items: center; align-items: center; height: 100vh;">

    {% include 'core/navbar.html' %}
    
    <h1 style="color: skyblue;">
        {% block title %}
        {% endblock title %}
    </h1>

    {% block content %}
    {% endblock content %}

    {% include 'core/footer.html' %}
</body>
</html>

core/templates/core/footer.html
<p style="position: fixed;
          bottom: 0;
          left: 0;
          right: 0;
          background-color: black;
          color: white;
          text-align: center">
    Hecho en Coderhouse 2025
</p>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
  Proyecto
{% endblock title %}

{% block content %}
  <div>
    <img style="width: 100%;
                    height: 50vh;
                    margin-top: 10vh"
             src="https://d1eipm3vz40hy0.cloudfront.net/images/SSAC-Blog/mercadotecnia-marketing-productos.jpg"
             alt="" />
  </div>  
{% endblock content %}

core/templates/core/navbar.html
<nav style="display: flex; justify-content: space-between; align-items: center;">
    <button>
        <a href="{% url 'core:index' %}">Home</a>
    </button>
    <button>
        <a href="{% url 'cliente:index' %}">Clientes</a>
    </button>
    <button>
        <a href="{% url 'producto:index' %}">Productos</a>
    </button>
</nav>

producto/templates/index.html
{% extends 'core/base.html' %}

{% block title %}
    Productos    
{% endblock title %}

{% block content %}

    <button>
        <a href="{% url 'producto:productocategoria_list' %}">Listar Categorías de Productos</a>
    </button>
    <button>
        <a href="{% url 'producto:productocategoria_create' %}">Crear Categoría de Productos</a>
    </button>

{% endblock content %}

producto/templates/productocategoria_create.html
{% extends 'core/base.html' %}

{% block title %}
    Productos: Crear Categoría de Productos
{% endblock title %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <button type="submit">Enviar</button>
        </table>
    </form>

{% endblock content %}

producto/templates/productocategoria_list.html
{% extends 'core/base.html' %}

{% block title %}
    Productos: Lista de categorías de productos
{% endblock title %}

{% block content %}
    <button>
        <a href="{% url 'producto:index' %}">Volver</a>
    </button>    
    {% for object in productocategoria %}
        <p> {{ object }} </p>
    {% endfor %}
{% endblock content %}